# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replicator_pb2 as replicator__pb2


class replStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.query = channel.unary_unary(
                '/replicator_package.repl/query',
                request_serializer=replicator__pb2.dml.SerializeToString,
                response_deserializer=replicator__pb2.rec.FromString,
                )


class replServicer(object):
    """Missing associated documentation comment in .proto file."""

    def query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_replServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'query': grpc.unary_unary_rpc_method_handler(
                    servicer.query,
                    request_deserializer=replicator__pb2.dml.FromString,
                    response_serializer=replicator__pb2.rec.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replicator_package.repl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class repl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replicator_package.repl/query',
            replicator__pb2.dml.SerializeToString,
            replicator__pb2.rec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
